"""fic please

Revision ID: 83cfa94a39b8
Revises: 3d6f2deb9f55
Create Date: 2024-03-29 12:28:02.347200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83cfa94a39b8'
down_revision: Union[str, None] = '3d6f2deb9f55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('face_reference', sa.Column('user_id1', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'face_reference', type_='foreignkey')
    op.create_foreign_key(None, 'face_reference', 'users', ['user_id1'], ['user_id'])
    op.drop_column('face_reference', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('face_reference', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'face_reference', type_='foreignkey')
    op.create_foreign_key(None, 'face_reference', 'users', ['user_id'], ['user_id'])
    op.drop_column('face_reference', 'user_id1')
    # ### end Alembic commands ###
